Commit to GH page even if error
To help debugging

diff --git a/.github/workflows/run_notebooks.yml b/.github/workflows/run_notebooks.yml
--- a/.github/workflows/run_notebooks.yml
+++ b/.github/workflows/run_notebooks.yml
@@ -35,13 +35,14 @@ jobs:
           yes | spinalcordtoolbox/install_sct
 
       - name: Run Jupyter Notebooks
+        continue-on-error: true  # Allow workflow to continue even if notebook execution fails
         run: |
           mkdir -p executed_notebooks
           for notebook in $(find . -name "*.ipynb"); do
             echo "Executing $notebook"
             jupyter nbconvert --to notebook --execute --inplace \
               --output executed_notebooks/$(basename $notebook) $notebook \
-              2>&1 | tee -a notebook_execution.log || exit 1
+              2>&1 | tee -a notebook_execution.log || echo "Execution failed for $notebook"
           done
 
       - name: Copy Executed Notebooks to Pages Directory
@@ -55,3 +56,8 @@ jobs:
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: gh-pages
+          publish_branch: gh-pages
+
+      - name: Success or Failure Message
+        if: failure()
+        run: echo "Notebooks executed with errors, but pushed to GitHub Pages."
